version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./feedback_system.db
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key-change-this}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - feedback_data:/app/data
    command: >
      sh -c "python create_demo_data.py && 
             uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:8000}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  feedback_data:
